In [2]:

from collections import deque

def bfs(graph, start):
    visited = set()
    queue = deque([start])

    while queue:
        vertex = queue.popleft()

        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)
            queue.extend(neighbor for neighbor in graph[vertex] if neighbor not in visited)

graph = {1:[0,2,3],2:[1,4,5],3:[0,1,4],4:[2,3,5],5:[2,4],0:[1,3]}

start_node = 0

print("BFS starting from node", start_node, ":")
bfs(graph, start_node)


BFS starting from node 0 :
0 1 3 2 4 5 

In [1]:
def dfs2(graph, start):
    visited = set()
    stack = [start]
    while stack:
        vertex = stack.pop()
        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)
            stack.extend(neighbor for neighbor in graph[vertex] if neighbor not in visited)

graph={
    'A':['B', 'S'],
    'B':['A'],
    'C':['D', 'E', 'F', 'S'],
    'D':['C'],
    'E':['C', 'H'],
    'F':['C', 'G'],
    'G':['F', 'H', 'S'],
    'H':['E', 'G'],
    'S':['A', 'C', 'G']
}

start_vertex='A'
print("DFS traversal starting from vertex", start_vertex, ":")
dfs2(graph, start_vertex)

DFS traversal starting from vertex A :
A S G H E C F D B 

In [12]:
import numpy as np
from queue import PriorityQueue

class Node:
    def __init__(self, state, parent=None, g_score=0, h_score=0):
        self.state = state
        self.parent = parent
        self.g_score = g_score
        self.h_score = h_score
        self.f_score = g_score + h_score

    def __lt__(self, other):
        return self.f_score < other.f_score

def heuristic(state, goal_state):
    return np.sum(state != goal_state)

def get_successors(state):
    successors = []
    zero_position = np.argwhere(state == 0)[0]  # Find the position of the zero in the state

    # Generate successor states by swapping the zero with its neighboring elements
    for move in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
        new_position = zero_position + move
        if 0 <= new_position[0] < state.shape[0] and 0 <= new_position[1] < state.shape[1]:
            successor_state = state.copy()
            successor_state[zero_position[0], zero_position[1]] = state[new_position[0], new_position[1]]
            successor_state[new_position[0], new_position[1]] = 0
            successors.append(successor_state)

    return successors

def astar(start_state, goal_state, heuristic):
    priority_queue = PriorityQueue()
    priority_queue.put((0, Node(start_state)))

    while not priority_queue.empty():
        _, current_node = priority_queue.get()

        if np.array_equal(current_node.state, goal_state):
            # Goal state reached, reconstruct path
            path = []
            while current_node:
                path.append(current_node.state)
                current_node = current_node.parent
            return path[::-1]

        for successor_state in get_successors(current_node.state):
            new_cost = current_node.g_score + 1
            new_node = Node(successor_state, parent=current_node, g_score=new_cost, h_score=heuristic(successor_state, goal_state))
            priority_queue.put((new_node.f_score, new_node))

    return None

initial_state = np.array([[2, 8, 3],
                          [1, 6, 4],
                          [7, 0, 5]])

goal_state = np.array([[1, 2, 3],
                       [8, 0, 4],
                       [7, 6, 5]])

result_path = astar(initial_state, goal_state, heuristic)

if result_path is not None:
    print("Solution found:")
    for state in result_path:
        print(state)
else:
    print("Goal state is not reachable.")


Solution found:
[[2 8 3]
 [1 6 4]
 [7 0 5]]
[[2 8 3]
 [1 0 4]
 [7 6 5]]
[[2 0 3]
 [1 8 4]
 [7 6 5]]
[[0 2 3]
 [1 8 4]
 [7 6 5]]
[[1 2 3]
 [0 8 4]
 [7 6 5]]
[[1 2 3]
 [8 0 4]
 [7 6 5]]
